version: '3.4'
services:
  db:
    image: sergiolbruno
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: slbruno-jwt
    ports:
      - "3308:3306"
    networks:
      - sergio-network
  slbruno-jwt:
    image: sergiolbruno/slbruno-jwt
    restart: always
    build: ./slbruno-jwt
    working_dir: /slbruno-jwt
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./slbruno-jwt:/slbruno-jwt
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - sergio-network
networks:
    sergio-network:
      driver: bridge